---
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
 - yarn install
 - yarn build